# 22. Generate Parentheses

import collections


# Backtrack
# Time: O(4^n/root(n))
# Space: O(n)
# 2023.08.04: no
# notes: classic backtracking, at each spot add '(' or ')'.
# prune when: 1. there are more ')' left than '(' left, return
# 2. either remaining count goes negative
class Solution:
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        results = []
        cur = []
        self.backtracking(n, n, cur, results)
        return results

    def backtracking(self, left, right, cur, results):
        if right < left:
            return
        if left < 0 or right < 0:
            return
        if left == 0 and right == 0:
            results.append("".join(cur))
            return

        cur.append('(')
        self.backtracking(left-1, right, cur, results)
        cur.pop()
        cur.append(')')
        self.backtracking(left, right-1, cur, results)
        cur.pop()


# Backtrack
# Time: O(4^n/root(n))
# Space: O(n)
# 2023.08.04: no
# notes: tighter than the one above, it only adds valid moves: add
# '(' while left < n, add ')' only while right < left, so the left
# bracket is always allowed and the right one is conditional
class Solution2:
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        answer = []
        def backtracking(cur_string, left_count, right_count):
            if len(cur_string) == 2 * n:
                answer.append("".join(cur_string))
                return
            if left_count < n:
                cur_string.append("(")
                backtracking(cur_string, left_count + 1, right_count)
                cur_string.pop()
            if right_count < left_count:
                cur_string.append(")")
                backtracking(cur_string, left_count, right_count + 1)
                cur_string.pop()
        backtracking([], 0, 0)
        return answer


# Brute force
# Time: O(2^2n*n)
# Space: O(n)
# 2023.08.04: no
# notes: generate every string of '(' and ')', keep the valid ones
class Solution3:
    def generateParenthesis(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        def isValid(p_string):
            left_count = 0
            for p in p_string:
                if p == '(':
                    left_count += 1
                else:
                    left_count -= 1

                if left_count < 0:
                    return False

            return left_count == 0

        answer = []
        queue = collections.deque([""])
        while queue:
            cur_string = queue.popleft()

            # If the length of cur_string is 2 * n, add it to `answer` if
            # it is valid.
            if len(cur_string) == 2 * n:
                if isValid(cur_string):
                    answer.append(cur_string)
                continue
            queue.append(cur_string + ")")
            queue.append(cur_string + "(")

        return answer


# Divide and Conquer
# Time: O(4^n/root(n))
# Space: O(n)
# 2023.08.04: no
# notes: the key is F(3) = "(" + F(0) + ")" + F(2)
#                       + "(" + F(1) + ")" + F(1)
#                       + "(" + F(2) + ")" + F(0)
# split by adding a pair of brackets on the left
class Solution4:
    def generateParenthesis(self, N):
        """
        :type N: int
        :rtype: List[str]
        """
        # @cache speeds it up at the cost of more space
        if N == 0: return ['']
        ans = []
        for c in range(N):
            lefts = self.generateParenthesis(c)
            for left in lefts:
                rights = self.generateParenthesis(N-1-c)
                for right in rights:
                    ans.append('({}){}'.format(left, right))
        return ans


# Solution 3 still need some explanation, come back in the future
# explaination: All valid parenthesis must contain "()" at some point,
# so the set of n+1 pairs of valid parenthesis can be generated by inserting "()"
# at each position for every elements of the set of n pairs of parenthesis
# N = 0 ""
# N = 1 "()"
# N = 2 "(()),()()"
# N = 3 "((())), (()()), (())(), ()(()), ()()()"


# Tests:
for sol in (Solution(), Solution2(), Solution3(), Solution4()):
    assert sorted(sol.generateParenthesis(1)) == ["()"]
    assert sorted(sol.generateParenthesis(2)) == ["(())", "()()"]
    assert sorted(sol.generateParenthesis(3)) == [
        "((()))", "(()())", "(())()", "()(())", "()()()"]
